export const logoImage  = require('./images/img_logo_sortecom.svg')

export const iconTag = require('./icons/ic_tag.png')
export const iconSearch=require('./icons/ic_search.svg')
export const iconNotification=require('./icons/ic_notification.svg')
export const iconSetting = require('./icons/ic_setting.svg')
export const iconExit = require('./icons/ic_exit.svg')
export const iconStar = require('./icons/ic_star.svg')
export const iconDelete = require('./icons/ic_delete.svg')
export const iconEdit = require('./icons/ic_edit.svg')
export const iconTutorial = require('./icons/ic_tutorial.svg')
export const iconCalendar = require('./icons/ic_calendar.svg')